// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gui.Models;

public partial class Driver
{
    public int Id { get; set; }

    public string Forename { get; set; }

    public string Surname { get; set; }

    public string PhoneNumber { get; set; }

    public string DriverLicenceSeries { get; set; }

    public string DriverLicenceNumber { get; set; }

    public string WhoAdded { get; set; }

    public DateTime WhenAdded { get; set; }

    public string WhoChanged { get; set; }

    public DateTime? WhenChanged { get; set; }

    public string Note { get; set; }

    public DateTime? IsDeleted { get; set; }
}