// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gui.Models;

public partial class Rate
{
    public int Id { get; set; }

    public string Forename { get; set; }

    public int DriverId { get; set; }

    public int VehicleId { get; set; }

    public int MovePrice { get; set; }

    public int IdlePrice { get; set; }

    public string WhoAdded { get; set; }

    public DateTime WhenAdded { get; set; }

    public string WhoChanged { get; set; }

    public DateTime? WhenChanged { get; set; }

    public string Note { get; set; }

    public DateTime? IsDeleted { get; set; }
}