// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gui.Models;

public partial class Route
{
    public int Id { get; set; }

    public string BoardingAddress { get; set; }

    public string DropAddress { get; set; }

    public string WhoAdded { get; set; }

    public DateTime WhenAdded { get; set; }

    public string WhoChanged { get; set; }

    public DateTime? WhenChanged { get; set; }

    public string Note { get; set; }

    public DateTime? IsDeleted { get; set; }
}