// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace gui.Models;

public partial class TransportVehicle
{
    public int Id { get; set; }

    public int DriverId { get; set; }

    public string Number { get; set; }

    public string Series { get; set; }

    public int RegistrationCode { get; set; }

    public string Model { get; set; }

    public string Color { get; set; }

    public string ReleaseYear { get; set; }

    public string WhoAdded { get; set; }

    public DateTime WhenAdded { get; set; }

    public string WhoChanged { get; set; }

    public DateTime? WhenChanged { get; set; }

    public string Note { get; set; }

    public DateTime? IsDeleted { get; set; }
}