networks:
  fullstack:

services:
 sqlserver-data:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=JcGDN9ST5KEG!
      - MSSQL_PID=Express
    ports:
      - 8002:1433
    networks:
      - fullstack

 sqlserver-credentials:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-credentials
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=JcGDN9ST5KEG!
      - MSSQL_PID=Express
    ports:
      - 8003:1433
    networks:
      - fullstack  
 src:
    container_name: src
    image: ${DOCKER_REGISTRY-}src
    build:
      context: ../../../
      dockerfile: Infrastructure/Docker/Dockerfile
    ports:
      - 5091:80
    depends_on:
      - sqlserver-data
      - sqlserver-credentials
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80 
      - DB_HOST1=sqlserver-data
      - DB_HOST2=sqlserver-credentials
      - DB_NAME1=Data
      - DB_NAME2=User_data
      - DB_SA_PASSWORD=JcGDN9ST5KEG!
      - LOG_PATH=logs/
      - SECRETS_PATH=Infrastructure/Secrets/;
    networks:
      - fullstack
 frontend:
    container_name: UI
    build:
      context: ../../../
      dockerfile: Presentation/Docker/Dockerfile
    ports:
      - 5000:81
    depends_on:
      - src
    networks:
      - fullstack